name: Build docker image

on: 
  push:
    branches: [main, develop, feature/deploy-action]
  pull_request:
    branches: [main, develop, feature/deploy-action]

jobs:
  build-iperf:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Compilation
        run: ./scripts/build-iperf.sh

      - name: Upload to artifacts
        run: |
          mkdir gh-artifacts
          mv iPerf/src/iperf gh-artifacts/
          chmod +x gh-artifacts/iperf
          ARTIFACT_NAME="iperf-2.0.13.${{ github.run_number }}"
          mkdir -p .github/variables
          echo "{\"variables\": [{\"name\": \"artifactName\",  \"value\": \"$ARTIFACT_NAME\"}]}" > .github/variables/variables.json
      
      - name: Set artifactName variable
        uses: deep-mm/set-variables@v1.0
        with:
          variableFileName: 'variables'
      
      - name: Upload apk to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifactName }}
          path: gh-artifacts/*
          
  speedtest-service:
    runs-on: ubuntu-20.04
    needs: build-iperf
    steps:
      - uses: actions/checkout@v2
      
      - name: Download result of the first job
        uses: actions/download-artifact@v2
        with:
          name: iperf-2.0.13.$GITHUB_RUN_NUMBER
      
      - name: Upload to artifacts
        run: |
          mkdir gh-artifacts/
          mv start_iperf.py gh-artifacts/
          mv iperf gh-artifacts/
          
          ARTIFACT_NAME="speedtest-service-$(cat VERSION)-$GITHUB_RUN_NUMBER"
          mkdir -p .github/variables
          echo "{\"variables\": [{\"name\": \"artifactName\",  \"value\": \"$ARTIFACT_NAME\"}]}" > .github/variables/variables.json
      
      - name: Set artifactName variable
        uses: deep-mm/set-variables@v1.0
        with:
          variableFileName: 'variables'
      
      - name: Upload apk to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifactName }}
          path: gh-artifacts/*
