name: Build iPerf

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04 # проверить
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Compilation
        run: ./build_scripts/iperf.sh

      - name: Upload to artifacts
        run: |
          mkdir gh-artifacts
          mv iPerf/src/iperf gh-artifacts/
          ARTIFACT_NAME="iperf-$(gh-artifacts/iperf -v 2>&1 | cut -d' ' -f3)-$GITHUB_RUN_NUMBER"
          mkdir -p .github/variables
          echo "{\"variables\": [{\"name\": \"artifactName\"}]}" > .github/variables/variables.json
      
      - name: Set artifactName variable
        uses: deep-mm/set-variables@v1.0
        with:
          variableFileName: 'variables'
      
      - name: Upload apk to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifactName }}
          path: gh-artifacts/*
